// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atsqmtujywmktqhifomq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0c3FtdHVqeXdta3RxaGlmb21xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDg0MTYsImV4cCI6MjA3MjAyNDQxNn0.lnxKhigJFIaTSbCIbLRaA7ITPuxNsvByjl0_e29c-Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});